name: Linux build

on:
  workflow_run:
    workflows: ["Validate project"]
    types:
      - completed

jobs:
  build:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      # Checkout (without LFS)
      - name: Checkout repository
        uses: actions/checkout@v4

      # Git LFS
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v3
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      # Cache
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          buildMethod: BuildScript.Build
          targetPlatform: StandaloneLinux64
          customParameters: -developerBuild true
          allowDirtyBuild: true

      # Output
      - name: Upload build to server
        uses: actions/upload-artifact@v3
        with:
          name: Linux Build
          path: |
            build/StandaloneLinux64/StandaloneLinux64_Data
            build/StandaloneLinux64/StandaloneLinux64
            build/StandaloneLinux64/UnityPlayer.so
            build/StandaloneLinux64/GameAssembly.so