name: Windows build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Windows Build
    runs-on: windows-2022
    steps:
      # Checkout (without LFS)
      - name: Checkout repository
        uses: actions/checkout@v4

      # Git LFS
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v3
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      # Cache
      - name: Caching
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Test
      #- name: Run tests
      #  uses: game-ci/unity-test-runner@v4
      #  env:
      #    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      #    UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      #    UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      #  with:
      #    githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          buildMethod: BuildScript.Build
          targetPlatform: StandaloneWindows64
          customParameters: -developmentBuild true
          allowDirtyBuild: true

      # Output
      - name: Upload build to server
        uses: actions/upload-artifact@v3
        with:
          name: Windows Build
          path: |
            build/StandaloneWindows64/StandaloneWindows64_Data
            build/StandaloneWindows64/baselib.dll
            build/StandaloneWindows64/GameAssembly.dll
            build/StandaloneWindows64/StandaloneWindows64.exe
            build/StandaloneWindows64/UnityCrashHandler64.exe
            build/StandaloneWindows64/UnityPlayer.dll